version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8080"
    # depends_on:
    #   - db
    environment:
      - "DB_CONNECTION=host=150.95.82.125 user=postgres password=P@ssword dbname=pos"
      - JWT_SECRET=0b84221cadfd321e547f74fc5b4940b1bb31bf2d58a411b3454c9b2908a1bf30
    volumes:
      - ./images:/images

  # db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: