version: "3.8"

services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8080"
    # depends_on:
    #   - db
    environment:
      - "DB_CONNECTION=host=150.95.82.125 user=postgres password=P@ssword dbname=pos"
      - JWT_SECRET=0b84221cadfd321e547f74fc5b4940b1bb31bf2d58a411b3454c9b2908a1bf30
      - INSTANT_IO_URL=http://instantio:3000/instantio/emit
    volumes:
      - ./images:/images
  instantio:
    restart: always
    image: htetlinmaung/instantio
    ports:
      - "8003:3000"
    environment:
      TOKEN_VERIFICATION_WEB_HOOK: "http://web:8080/api/auth/verify-token"
      # INSTANTIO_WEB_HOOK: "http://web:8080/api/update-instantio-state"
      TZ: "Asia/Yangon"
      SOCKETIO_NAMESPACES: "/pos"

  # db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
