version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      - "DB_CONNECTION=host=localhost user=postgres password=<password> dbname=<dbname>"
      - JWT_SECRET=<secret>
    volumes:
      - ./images:/images

  # db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
